```mermaid
graph TD
    "5GMM-DEREGISTERED"["5GMM-DEREGISTERED (state)"] -->|"Initial_Registration_Triggers"| "Initiate_Registration_Procedure"
    "Initiate_Registration_Procedure"["Initiate_Registration_Procedure (action)"] -->|"Initiate Registration"| "Send_REGISTRATION_REQUEST"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Start Timer"| "Timer_T3510_Started"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Stop Timer (condition:If timer T3502 is running)"| "Timer_T3502_Stopped"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Stop Timer (condition:If timer T3511 is running)"| "Timer_T3511_Stopped"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Handle 5GS Mobile Identity"| "Handling_5GS_Mobile_Identity"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "UE_Operating_Dual_Registration_Mode"
    "UE_Operating_Dual_Registration_Mode"["UE_Operating_Dual_Registration_Mode (condition)"] -->|"Include UE status IE (condition:TRUE)"| "Include_UE_Status_IE"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "Last_Visited_TAI_Available"
    "Last_Visited_TAI_Available"["Last_Visited_TAI_Available (condition)"] -->|"Include last visited registered TAI (condition:TRUE)"| "Include_Last_Visited_TAI"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "Request_SMS_Over_NAS"
    "Request_SMS_Over_NAS"["Request_SMS_Over_NAS (condition)"] -->|"Include 5GS update type IE (condition:TRUE)"| "Include_5GS_Update_Type_IE"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "UE_Supports_MICO_Mode"
    "UE_Supports_MICO_Mode"["UE_Supports_MICO_Mode (condition)"] -->|"Include MICO indication IE (condition:TRUE)"| "Include_MICO_Indication_IE"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "UE_Needs_UE_Specific_DRX"
    "UE_Needs_UE_Specific_DRX"["UE_Needs_UE_Specific_DRX (condition)"] -->|"Include Requested DRX parameters IE (condition:TRUE)"| "Include_Requested_DRX_Parameters_IE"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "UE_Supports_eDRX"
    "UE_Supports_eDRX"["UE_Supports_eDRX (condition)"] -->|"Include Requested extended DRX parameters IE (condition:TRUE)"| "Include_Requested_Extended_DRX_Parameters_IE"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "UE_Requests_LADN_Information"
    "UE_Requests_LADN_Information"["UE_Requests_LADN_Information (condition)"] -->|"Include LADN indication IE (condition:TRUE)"| "Include_LADN_Indication_IE"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "UE_Requests_NSSAI"
    "UE_Requests_NSSAI"["UE_Requests_NSSAI (condition)"] -->|"Include Requested NSSAI IE (condition:TRUE)"| "Include_Requested_NSSAI_IE"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "UE_Supports_NSAG"
    "UE_Supports_NSAG"["UE_Supports_NSAG (condition)"] -->|"set NSAG bit (condition:TRUE)"| "Set_NSAG_Bit"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "Initial_Registration_Emergency_Services"
    "Initial_Registration_Emergency_Services"["Initial_Registration_Emergency_Services (condition)"] -->|"set Follow-on request indicator (condition:TRUE)"| "Set_Follow_On_Request_Indicator"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "UE_supports_S1_mode"
    "UE_supports_S1_mode"["UE_supports_S1_mode (condition)"] -->|"Set S1 mode bit (condition:TRUE)"| "Set_S1_mode_bit"
    "UE_supports_S1_mode"["UE_supports_S1_mode (condition)"] -->|"Include S1 UE network capability IE (condition:TRUE)"| "Include_S1_UE_network_capability_IE"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "UE_supports_LPP_in_N1_mode"
    "UE_supports_LPP_in_N1_mode"["UE_supports_LPP_in_N1_mode (condition)"] -->|"Set LPP bit (condition:TRUE)"| "Set_LPP_bit"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "UE_supports_ciphered_broadcast_data"
    "UE_supports_ciphered_broadcast_data"["UE_supports_ciphered_broadcast_data (condition)"] -->|"Include additional information requested IE (condition:TRUE)"| "Include_Additional_information_requested_IE"
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"] -->|"Check conditions"| "UE_supports_WUSA"
    "UE_supports_WUSA"["UE_supports_WUSA (condition)"] -->|"Set WUSA bit (condition:TRUE)"| "Set_WUSA_bit"
    "5GMM-DEREGISTERED"["5GMM-DEREGISTERED (state)"]
    "Initiate_Registration_Procedure"["Initiate_Registration_Procedure (action)"]
    "Send_REGISTRATION_REQUEST"["Send_REGISTRATION_REQUEST (action)"]
    "Initial_Registration_Triggers"["Initial_Registration_Triggers (event)"]
    "Timer_T3510_Started"["Timer_T3510_Started (action)"]
    "Timer_T3502_Stopped"["Timer_T3502_Stopped (action)"]
    "Timer_T3511_Stopped"["Timer_T3511_Stopped (action)"]
    "Handling_5GS_Mobile_Identity"["Handling_5GS_Mobile_Identity (action)"]
    "UE_Operating_Dual_Registration_Mode"["UE_Operating_Dual_Registration_Mode (condition)"]
    "Include_UE_Status_IE"["Include_UE_Status_IE (action)"]
    "Last_Visited_TAI_Available"["Last_Visited_TAI_Available (condition)"]
    "Include_Last_Visited_TAI"["Include_Last_Visited_TAI (action)"]
    "Request_SMS_Over_NAS"["Request_SMS_Over_NAS (condition)"]
    "Include_5GS_Update_Type_IE"["Include_5GS_Update_Type_IE (action)"]
    "UE_Supports_MICO_Mode"["UE_Supports_MICO_Mode (condition)"]
    "Include_MICO_Indication_IE"["Include_MICO_Indication_IE (action)"]
    "UE_Needs_UE_Specific_DRX"["UE_Needs_UE_Specific_DRX (condition)"]
    "Include_Requested_DRX_Parameters_IE"["Include_Requested_DRX_Parameters_IE (action)"]
    "UE_Supports_eDRX"["UE_Supports_eDRX (condition)"]
    "Include_Requested_Extended_DRX_Parameters_IE"["Include_Requested_Extended_DRX_Parameters_IE (action)"]
    "UE_Requests_LADN_Information"["UE_Requests_LADN_Information (condition)"]
    "Include_LADN_Indication_IE"["Include_LADN_Indication_IE (action)"]
    "UE_Requests_NSSAI"["UE_Requests_NSSAI (condition)"]
    "Include_Requested_NSSAI_IE"["Include_Requested_NSSAI_IE (action)"]
    "UE_Supports_NSAG"["UE_Supports_NSAG (condition)"]
    "Set_NSAG_Bit"["Set_NSAG_Bit (action)"]
    "Initial_Registration_Emergency_Services"["Initial_Registration_Emergency_Services (condition)"]
    "Set_Follow_On_Request_Indicator"["Set_Follow_On_Request_Indicator (action)"]
    "UE_supports_S1_mode"["UE_supports_S1_mode (condition)"]
    "Set_S1_mode_bit"["Set_S1_mode_bit (action)"]
    "Include_S1_UE_network_capability_IE"["Include_S1_UE_network_capability_IE (action)"]
    "UE_supports_LPP_in_N1_mode"["UE_supports_LPP_in_N1_mode (condition)"]
    "Set_LPP_bit"["Set_LPP_bit (action)"]
    "UE_supports_ciphered_broadcast_data"["UE_supports_ciphered_broadcast_data (condition)"]
    "Include_Additional_information_requested_IE"["Include_Additional_information_requested_IE (action)"]
    "UE_supports_WUSA"["UE_supports_WUSA (condition)"]
    "Set_WUSA_bit"["Set_WUSA_bit (action)"]
```