```mermaid
graph LR
    "5GMM_DEREGISTERED"["5GMM-DEREGISTERED (state)"]
    "Registration_Initiation"["Initiate Registration Procedure (action)"]
    "Registration_Request_Sent"["REGISTRATION REQUEST (event)"]
    "Timer_Start_T3510"["Start timer T3510 (action)"]
    "Timer_Stop_T3502"["Stop timer T3502 (action)"]
    "Timer_Stop_T3511"["Stop timer T3511 (action)"]

    "5GMM_DEREGISTERED" --> |Conditions_Met (Initial registration for 5GS services,Initial registration for emergency services,Initial registration for SMS over NAS,Move from GERAN/UTRAN to NG-RAN coverage,Initial registration for onboarding services in SNPN,Initial registration for disaster roaming services,Initial registration to come out of unavailability period and resume normal services)| "Registration_Initiation"
    "Registration_Initiation" --> |SendREGISTRATIONREQUESTmessage| "Registration_Request_Sent"
    "Registration_Request_Sent" --> |TimerT3510Started| "Timer_Start_T3510"
    "Registration_Request_Sent" --> |TimerT3502Stopped(ifrunning)| "Timer_Stop_T3502"
    "Registration_Request_Sent" --> |TimerT3511Stopped(ifrunning)| "Timer_Stop_T3511"
```