graph LR
    A["UE (5GMM-DEREGISTERED)"] --> B{"REGISTRATION REQUEST"}
    B --> C["AMF"]
    C --> D{"Authentication (Conditional)"}
    D--"Authentication Successful"-->E{"Security Mode Control"}
    D--"Authentication Skipped"-->E
    E --> F{"REGISTRATION ACCEPT"}
    F --> G["UE (5GMM-REGISTERED)"]
    C -- "Authentication Failure" --> H{"REGISTRATION REJECT"}
    H --> A
    G --> I{"REGISTRATION COMPLETE (Conditional)"}
    I --> C

    style B fill:#ccf,stroke:#333,stroke-width:2px
    style F fill:#ccf,stroke:#333,stroke-width:2px