flowchart TD
5GMM_DEREGISTERED -->|"action: sends a REGISTRATION REQUEST message to the AMF"| REGISTRATION_REQUEST_sent
REGISTRATION_REQUEST_sent -->|"action: starts timer T3510"| Awaiting_REGISTRATION_ACCEPT_REJECT
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\naction: resets the registration attempt counter; sets the 5GS update status to 5U1 UPDATED"| 5GMM_REGISTERED
5GMM_REGISTERED -->|"condition: 5GS registration result value indicates '3GPP access'; UE is in 5GMM-REGISTERED state over non-3GPP access and on the same PLMN or SNPN as 3GPP access\naction: sets the 5GS update status to 5U2 NOT UPDATED over non-3GPP access"| 5GMM_DEREGISTERED_ATTEMPTING_REGISTRATION
5GMM_REGISTERED -->|"condition: 5GS registration result value indicates 'Non-3GPP access'; UE is in 5GMM-REGISTERED state over 3GPP access and is on the same PLMN or SNPN as non-3GPP access\naction: sets the 5GS update status to 5U2 NOT UPDATED over 3GPP access"| 5GMM_DEREGISTERED_ATTEMPTING_REGISTRATION
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\ncondition: received 'CAG information list' includes registered PLMN; REGISTRATION ACCEPT via CAG cell; no authorized CAG-ID(s); no indication that 5GS access is only via CAG cells\naction: searches for a suitable cell according to 3GPP TS 38.304 [28] or 3GPP TS 36.304 [25C] with the updated 'CAG information list'"| 5GMM_REGISTERED_LIMITED_SERVICE
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\ncondition: received 'CAG information list' includes registered PLMN; REGISTRATION ACCEPT via CAG cell; no authorized CAG-ID(s); indication that 5GS access is only via CAG cells; one or more authorized CAG-ID(s)\naction: searches for a suitable cell according to 3GPP TS 38.304 [28] with the updated 'CAG information list'"| 5GMM_REGISTERED_LIMITED_SERVICE
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\ncondition: received 'CAG information list' includes registered PLMN; REGISTRATION ACCEPT via CAG cell; no authorized CAG-ID(s); indication that 5GS access is only via CAG cells; no emergency registration; initial registration not for handover of emergency PDU session\naction: applies the PLMN selection process defined in 3GPP TS 23.122 [5] with the updated 'CAG information list'"| 5GMM_REGISTERED_PLMN_SEARCH
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\ncondition: received 'CAG information list' includes registered PLMN; REGISTRATION ACCEPT via non-CAG cell; indication that 5GS access is only via CAG cells; no authorized CAG-ID(s); no emergency registration; initial registration not for handover of emergency PDU session\naction: applies the PLMN selection process defined in 3GPP TS 23.122 [5] with the updated 'CAG information list'"| 5GMM_REGISTERED_PLMN_SEARCH
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\ncondition: received 'CAG information list' includes registered PLMN; REGISTRATION ACCEPT via non-CAG cell; indication that 5GS access is only via CAG cells; one or more authorized CAG-ID(s)\naction: searches for a suitable cell according to 3GPP TS 38.304 [28] with the updated 'CAG information list'"| 5GMM_REGISTERED_LIMITED_SERVICE
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\ncondition: received 'CAG information list' does not include registered PLMN; REGISTRATION ACCEPT via CAG cell\naction: searches for a suitable cell according to 3GPP TS 38.304 [28] or 3GPP TS 36.304 [25C] with the updated 'CAG information list'"| 5GMM_REGISTERED_LIMITED_SERVICE
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\ncondition: REGISTRATION ACCEPT message contains Network slicing indication IE with Network slicing subscription change indication set to 'Network slicing subscription changed'\naction: returns a REGISTRATION COMPLETE message to the AMF"| REGISTRATION_COMPLETE_sent
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\ncondition: RCMAN bit set to 'Sending of REGISTRATION COMPLETE message for NSAG information supported'; REGISTRATION ACCEPT message contains NSAG information IE\naction: returns REGISTRATION COMPLETE message to the AMF"| REGISTRATION_COMPLETE_sent
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\ncondition: REGISTRATION ACCEPT message contains CAG information list IE or Extended CAG information list IE; CAG bit set to 'CAG supported'\naction: returns a REGISTRATION COMPLETE message to the AMF"| REGISTRATION_COMPLETE_sent
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\ncondition: RCMAP bit set to 'Sending of REGISTRATION COMPLETE message for negotiated PEIPS parameters supported'; REGISTRATION ACCEPT message contains Negotiated PEIPS assistance information IE\naction: returns REGISTRATION COMPLETE message to the AMF"| REGISTRATION_COMPLETE_sent
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION ACCEPT message received\ncondition: REGISTRATION ACCEPT message contains UE radio capability ID IE or UE radio capability ID deletion indication IE\naction: returns a REGISTRATION COMPLETE message to the AMF"| REGISTRATION_COMPLETE_sent
REGISTRATION_COMPLETE_sent -->|"event: REGISTRATION COMPLETE message received\naction: stops timer T3550"| 5GMM_REGISTERED
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"event: REGISTRATION REJECT message received\ncondition: REGISTRATION REJECT message includes 5GMM cause #5 'PEI not accepted'"| 5GMM_DEREGISTERED_NO_SUPI
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"action: aborts the initial registration procedure; sets the 5GS update status to 5U2 NOT UPDATED; resets the registration attempt counter"| 5GMM_DEREGISTERED_ATTEMPTING_REGISTRATION
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"action: aborts the initial registration procedure; sets the 5GS update status to 5U2 NOT UPDATED"| 5GMM_DEREGISTERED_PLMN_SEARCH
Awaiting_REGISTRATION_ACCEPT_REJECT -->|"action: enables the E-UTRA capability if it was disabled; disables the N1 mode capability for 3GPP access"| 5GMM_DEREGISTERED_NO_CELL_AVAILABLE
5GMM_REGISTERED_INITIATED -->|"event: DEREGISTRATION REQUEST message received\ncondition: UE is in state 5GMM-REGISTERED-INITIATED\naction: aborts the de-registration procedure; progresses the initial registration procedure"| REGISTRATION_REQUEST_sent
5GMM_DEREGISTERED_ATTEMPTING_REGISTRATION -->|"event: REGISTRATION ACCEPT message received\naction: resets the registration attempt counter; sets the 5GS update status to 5U1 UPDATED"| 5GMM_REGISTERED
5GMM_DEREGISTERED_ATTEMPTING_REGISTRATION -->|"action: aborts the initial registration procedure; sets the 5GS update status to 5U2 NOT UPDATED; resets the registration attempt counter"| 5GMM_DEREGISTERED_ATTEMPTING_REGISTRATION
5GMM_DEREGISTERED_ATTEMPTING_REGISTRATION -->|"action: aborts the initial registration procedure; sets the 5GS update status to 5U2 NOT UPDATED"| 5GMM_DEREGISTERED_PLMN_SEARCH